<div class="content">
	<form class="form" novalidate onsubmit="return false">
		<h2 class="text-center">Feedback</h2>

		<div class="form-group">
			<label for="nameInput">Name:</label>
			<input type="text" class="form-control" id="nameInput" name="name" placeholder="Enter your name" maxlength="15" aria-describedby="nameHelpBlock">
			<span id="emailHelpBlock" class="help-block"></span>
		</div>

		<div class="form-group">
			<label for="emailInput">Email address:</label>
			<input type="email" class="form-control" id="emailInput" name="email" placeholder="Enter your email address" maxlength="120" aria-describedby="emailHelpBlock">
			<span id="emailHelpBlock" class="help-block"></span>
		</div>

		<div class="form-group">
			<label for="messageInput">Message:</label>
			<textarea class="form-control" id="messageInput" name="message" placeholder="Write your message" cols="30" maxlength="1000" aria-describedby="messageHelpBlock"></textarea>
			<span id="emailHelpBlock" class="help-block"></span>
		</div>

		<button type="submit" class="btn btn-primary">Submit</button>
	</form>

	<div class="alert alert-success" role="alert"></div>
</div>

<script src="/js/index.js?v=1" type="text/javascript"></script>

